### ISSUE TITLE
Yafc fails to save a pY-AE project

### ISSUE THREAD

**Issue by shpaass** [shpaass/yafc-ce#245]
Steps to reproduce:
1. Checkout to 7d55f43e58e48a8d031c4980ea237097a659ab70. I did a [bisection](https://github.com/shpaass/yafc-ce/pull/244#issuecomment-2307650036), and this was the first commit where the bug is present.
2. Download the attached save [sample.txt](https://github.com/user-attachments/files/16732897/sample.txt), change its extension to `.zip` and sync mods with it. GitHub does not accept custom extensions, so I had to pass it as txt. Its sha256 is `c00fc46997e4c55b0dc34eb61ae6a830e34f17fd3ebb87862cd6fedde923dfed`.
3. Alternatively, the bug is likely to be reproduced on a generic pY-AE mod folder.
4. Download the attached [project.txt](https://github.com/user-attachments/files/16732829/project.txt). Change its extension to `.yafc`. Its sha256 is `218747a1db8af36fd7d05a1b5ab676e8dbdce235f2f5902af83c8cc3d0ebe0fa`.
5. Alternatively, you can try to reproduce the bug on the project file that was last-saved prior to 7d55f43e58e48a8d031c4980ea237097a659ab70. This bug is not reproducible for the projects that were created after it.
6. Open the attached project.
7. Add or delete a row in any sheet. Adding or deleting pages also works, but the rows were tested for this particular case.
8. Try to save the project. Receive the following error:
```
Yafc.Model.ProductionTable.modules must not return null.

   at Yafc.Model.PropertySerializer`2.getter(TOwner owner) in .\Yafc.Model\Serialization\PropertySerializers.cs:line 61
   at Yafc.Model.ReadOnlyReferenceSerializer`2.SerializeToJson(TOwner owner, Utf8JsonWriter writer) in .\Yafc.Model\Serialization\PropertySerializers.cs:line 102
   at Yafc.Model.SerializationMap`1.SerializeToJson(T value, Utf8JsonWriter writer) in .\Yafc.Model\Serialization\SerializationMap.cs:line 229
   at Yafc.Model.ModelObjectSerializer`1.WriteToJson(Utf8JsonWriter writer, T value) in .\Yafc.Model\Serialization\ValueSerializers.cs:line 113
   at Yafc.Model.ValuePropertySerializer`2.SerializeToJson(TOwner owner, Utf8JsonWriter writer) in .\Yafc.Model\Serialization\PropertySerializers.cs:line 74
   at Yafc.Model.SerializationMap`1.SerializeToJson(T value, Utf8JsonWriter writer) in .\Yafc.Model\Serialization\SerializationMap.cs:line 229
   at Yafc.Model.ModelObjectSerializer`1.WriteToJson(Utf8JsonWriter writer, T value) in .\Yafc.Model\Serialization\ValueSerializers.cs:line 113
   at Yafc.Model.CollectionSerializer`3.SerializeToJson(TOwner owner, Utf8JsonWriter writer) in .\Yafc.Model\Serialization\PropertySerializers.cs:line 171
   at Yafc.Model.SerializationMap`1.SerializeToJson(T value, Utf8JsonWriter writer) in .\Yafc.Model\Serialization\SerializationMap.cs:line 229
   at Yafc.Model.SerializationMap`1.SpecificSerializationMap.SerializeToJson(Object target, Utf8JsonWriter writer) in .\Yafc.Model\Serialization\SerializationMap.cs:line 86
   at Yafc.Model.ReadOnlyReferenceSerializer`2.SerializeToJson(TOwner owner, Utf8JsonWriter writer) in .\Yafc.Model\Serialization\PropertySerializers.cs:line 110
   at Yafc.Model.SerializationMap`1.SerializeToJson(T value, Utf8JsonWriter writer) in .\Yafc.Model\Serialization\SerializationMap.cs:line 229
   at Yafc.Model.ModelObjectSerializer`1.WriteToJson(Utf8JsonWriter writer, T value) in .\Yafc.Model\Serialization\ValueSerializers.cs:line 113
   at Yafc.Model.CollectionSerializer`3.SerializeToJson(TOwner owner, Utf8JsonWriter writer) in .\Yafc.Model\Serialization\PropertySerializers.cs:line 171
   at Yafc.Model.SerializationMap`1.SerializeToJson(T value, Utf8JsonWriter writer) in .\Yafc.Model\Serialization\SerializationMap.cs:line 229
   at Yafc.Model.Project.Save(String fileName) in .\Yafc.Model\Model\Project.cs:line 112
   at Yafc.MainScreen.SaveProject() in .\Yafc\Windows\MainScreen.cs:line 649
   at Yafc.MainScreen.KeyDown(SDL_Keysym key) in .\Yafc\Windows\MainScreen.cs:line 574
   at Yafc.UI.InputSystem.KeyDown(SDL_Keysym key) in .\Yafc.UI\Core\InputSystem.cs:line 81
   at Yafc.UI.Ui.ProcessEvents() in .\Yafc.UI\Core\Ui.cs:line 110
```
Pinging @DaleStan just in case.

**Comment by shpaass** [comment]
Did a couple of edits to the tickets.
