### ISSUE TITLE
Cannot save

### ISSUE THREAD

**Issue by Dorus** [shpaass/yafc-ce#246]
Latest master, need to investigate why this happens, not in any state to do so right now so i'll just dump everything here.

> Yafc.Model.ProductionTable.modules must not return null.

   at Yafc.Model.PropertySerializer`2.getter(TOwner owner) in .\Yafc.Model\Serialization\PropertySerializers.cs:line 61
   at Yafc.Model.ReadOnlyReferenceSerializer`2.SerializeToJson(TOwner owner, Utf8JsonWriter writer) in .\Yafc.Model\Serialization\PropertySerializers.cs:line 102
   at Yafc.Model.SerializationMap`1.SerializeToJson(T value, Utf8JsonWriter writer) in .\Yafc.Model\Serialization\SerializationMap.cs:line 229
   at Yafc.Model.SerializationMap`1.SerializeToJson(T value, Utf8JsonWriter writer) in .\Yafc.Model\Serialization\SerializationMap.cs:line 229
   at Yafc.Model.CollectionSerializer`3.SerializeToJson(TOwner owner, Utf8JsonWriter writer) in .\Yafc.Model\Serialization\PropertySerializers.cs:line 171
   at Yafc.Model.SerializationMap`1.SerializeToJson(T value, Utf8JsonWriter writer) in .\Yafc.Model\Serialization\SerializationMap.cs:line 229
   at Yafc.Model.SerializationMap`1.SpecificSerializationMap.SerializeToJson(Object target, Utf8JsonWriter writer) in .\Yafc.Model\Serialization\SerializationMap.cs:line 86
   at Yafc.Model.ReadOnlyReferenceSerializer`2.SerializeToJson(TOwner owner, Utf8JsonWriter writer) in .\Yafc.Model\Serialization\PropertySerializers.cs:line 110
   at Yafc.Model.SerializationMap`1.SerializeToJson(T value, Utf8JsonWriter writer) in .\Yafc.Model\Serialization\SerializationMap.cs:line 229
   at Yafc.Model.CollectionSerializer`3.SerializeToJson(TOwner owner, Utf8JsonWriter writer) in .\Yafc.Model\Serialization\PropertySerializers.cs:line 171
   at Yafc.Model.SerializationMap`1.SerializeToJson(T value, Utf8JsonWriter writer) in .\Yafc.Model\Serialization\SerializationMap.cs:line 229
   at Yafc.Model.Project.Save(String fileName) in .\Yafc.Model\Model\Project.cs:line 112
   at Yafc.MainScreen.SaveProject() in .\Yafc\Windows\MainScreen.cs:line 649
   at Yafc.MainScreen.KeyDown(SDL_Keysym key) in .\Yafc\Windows\MainScreen.cs:line 574
   at Yafc.UI.InputSystem.KeyDown(SDL_Keysym key) in .\Yafc.UI\Core\InputSystem.cs:line 79
   at Yafc.UI.Ui.ProcessEvents() in .\Yafc.UI\Core\Ui.cs:line 110

![afbeelding](https://github.com/user-attachments/assets/05180617-ab73-49a6-a440-5d9bfdf8a7a4)

**Comment by shpaass** [comment]
Already being investigated.
https://github.com/shpaass/yafc-ce/pull/244#issuecomment-2305791685
https://github.com/shpaass/yafc-ce/commit/eeec967cd098670a192700855d4bee1918c34454#comments

**Comment by shpaass** [comment]
https://github.com/shpaass/yafc-ce/issues/245

**Comment by shpaass** [comment]
Fixed by #247
