### ISSUE TITLE
Space Age - Spoilage

### ISSUE THREAD

**Issue by SWeini** [shpaass/yafc-ce#313]
Support spoilage mechanic

- [ ] Mark spoilable items in GUI (ItemPrototype::spoil_result/spoil_to_trigger_result)
- [ ] Mark spoil result items in GUI
Is this really needed? There is ItemPrototypeFlags "spoil-result", but I don't know what it does.
- [x] Create a recipe for ItemPrototype::spoil_result, allows automation of spoilable items
- [x] Add spoilage recipes to NEIE (and to "add consumption/production recipe" dropdowns)
- [ ] Support ItemPrototype::spoil_to_trigger_result, but triggers are quite difficult to support because they are so rich
Used for eggs spoiling into enemies (doesn't make sense in planning)
Used for captivated spawners into normal spawners (doesn't make sense in planning)
- [ ] Support RecipePrototype::result_is_always_fresh and ItemProductPrototype::percent_spoiled
Unless we want to model the spoilage of all items and allow adding configurable timespans for transportation, this would only be for information
- [ ] Support spoilable science packs
I didn't see anything in the API for this, and I haven't been to Gleba yet, but I believe this is a thing
- [ ] RecipePrototype::preserve_products_in_machine_output
Some products don't start spoiling until taken out of the machine.

**Comment by shpaass** [comment]
On a side note, I don't know why Github considered these issues resolved. Their numbers were not mentioned in the PR, from what I remember.

**Comment by shpaass** [comment]
Ah, I see. The Linked Issues part on the side.

**Comment by sunrosa** [comment]
If an item spoils into a module it creates a critical error
```
Unable to cast object of type 'Yafc.Model.Item' to type 'Yafc.Model.Module'.
at Yafc.Parser.FactorioDataDeserializer.GetObject[TNominal,TActual](String name) in .\Yafc.Parser\Data\FactorioDataDeserializer_Context.cs:line 94
at Yafc.Parser.FactorioDataDeserializer.DeserializeItem(LuaTable table, ErrorCollector _) in .\Yafc.Parser\Data\FactorioDataDeserializer.cs:line 373
at Yafc.Parser.FactorioDataDeserializer.DeserializePrototypes(LuaTable data, String type, Action`2 deserializer, IProgress`1 progress, ErrorCollector errorCollector) in .\Yafc.Parser\Data\FactorioDataDeserializer.cs:line 311
at Yafc.Parser.FactorioDataDeserializer.LoadData(String projectPath, LuaTable data, LuaTable prototypes, Boolean netProduction, IProgress`1 progress, ErrorCollector errorCollector, Boolean renderIcons) in .\Yafc.Parser\Data\FactorioDataDeserializer.cs:line 121
at Yafc.Parser.FactorioDataSource.Parse(String factorioPath, String modPath, String projectPath, Boolean netProduction, IProgress`1 progress, ErrorCollector errorCollector, String locale, Boolean renderIcons) in .\Yafc.Parser\FactorioDataSource.cs:line 354
at Yafc.WelcomeScreen.LoadProject() in .\Yafc\Windows\WelcomeScreen.cs:line 388
```

This is reproducible using pyanodons hard mode 1.3.1. This error does not get thrown on pyhard 1.2.5

**Comment by CricketBr** [comment]
Suggestion: Add text to mouseover to say what the item spoils into, and how long it takes. Just having that information would save a lot of flipping between YAFC and other screens, even if YAFC doesn't use it in any calculations. The captive biter spawner should also show how long before it starves, assuming it starts at full health and receives no damage.

(I can't think of a way to show spoilage over time in math, but remain hopeful.)

**Comment by apia46** [comment]
You definintely know about this already but I figured it would make sense to say here that the solver can't see spoilage recipes for some reason
![{4F511503-8F94-4184-B5C1-43DAA81F5979}](https://github.com/user-attachments/assets/66b9a24a-e103-41d0-95b6-f0cf35c45d4f)
