### ISSUE TITLE
Intermittent crash when loading alien biomes

### ISSUE THREAD

**Issue by branan** [shpaass/yafc-ce#373]
I'm not sure if this will crash only with alien biomes, or if it requires other mods from my stack. Getting a minimal reproducer on a inconsistent crash is a pain.

Every once in a while I get this error while YAFC is loading alien biomes:
```
Sequence contains no matching element
   at System.Linq.ThrowHelper.ThrowNoMatchException()
   at System.Linq.Enumerable.Single[TSource](IEnumerable`1 source, Func`2 predicate)
   at Yafc.Parser.FactorioDataDeserializer.DeserializeLocation(LuaTable table, ErrorCollector collector) in ./Yafc.Parser/Data/FactorioDataDeserializer.cs:line 583
   at Yafc.Parser.FactorioDataDeserializer.DeserializePrototypes(LuaTable data, String type, Action`2 deserializer, IProgress`1 progress, ErrorCollector errorCollector) in ./Yafc.Parser/Data/FactorioDataDeserializer.cs:line 325
   at Yafc.Parser.FactorioDataDeserializer.LoadData(String projectPath, LuaTable data, LuaTable prototypes, Boolean netProduction, IProgress`1 progress, ErrorCollector errorCollector, Boolean renderIcons) in ./Yafc.Parser/Data/FactorioDataDeserializer.cs:line 136
   at Yafc.Parser.FactorioDataSource.Parse(String factorioPath, String modPath, String projectPath, Boolean netProduction, IProgress`1 progress, ErrorCollector errorCollector, String locale, Boolean renderIcons) in ./Yafc.Parser/FactorioDataSource.cs:line 354
   at Yafc.WelcomeScreen.LoadProject() in ./Yafc/Windows/WelcomeScreen.cs:line 396
```

I added a bit of debug printing locally, and it only seems to crash on the `vegetation-olive-grass-2` tile.

Other info:
Dotnet 8.0.110 on Linux (Arch)

**Comment by veger** [comment]
Thanks for the follow up. Glad to hear it is fixed now.
