### ISSUE TITLE
Unable to load project (forever) after marking an entity as accessible manually

### ISSUE THREAD

**Issue by sunrosa** [shpaass/yafc-ce#379]
YAFC 2.4.0

It was an old project that I was migrating from a YAFC version from a few months ago. But then I tried it again with a completely new project. It bricked that one too. I believe it was the Mova Plant entity that I was marking.

Should be reproducible for anyone.
1. Create new project
2. Mark Mova Plant entity as accessible
3. Get error popup
4. Project can never be loaded again

If someone can figure out how to unbrick my main save, that would be nice.

```
Sequence contains no elements
   at System.Linq.ThrowHelper.ThrowNoElementsException()
   at System.Linq.Enumerable.Min[TSource,TResult](IEnumerable`1 source, Func`2 selector)
   at Yafc.Model.DependencyNode.AndNode.IsAutomatable(Func`2 isAutomatable, AutomationStatus automationState) in .\Yafc.Model\Analysis\DependencyNode.cs:line 140
   at Yafc.Model.AutomationAnalysis.Compute(Project project, ErrorCollector warnings) in .\Yafc.Model\Analysis\AutomationAnalysis.cs:line 53
   at Yafc.Model.Analysis.ProcessAnalyses(IProgress`1 progress, Project project, ErrorCollector errors) in .\Yafc.Model\Analysis\Analysis.cs:line 20
   at Yafc.Parser.FactorioDataDeserializer.LoadData(String projectPath, LuaTable data, LuaTable prototypes, Boolean netProduction, IProgress`1 progress, ErrorCollector errorCollector, Boolean renderIcons) in .\Yafc.Parser\Data\FactorioDataDeserializer.cs:line 174
   at Yafc.Parser.FactorioDataSource.Parse(String factorioPath, String modPath, String projectPath, Boolean netProduction, IProgress`1 progress, ErrorCollector errorCollector, String locale, Boolean renderIcons) in .\Yafc.Parser\FactorioDataSource.cs:line 354
   at Yafc.WelcomeScreen.LoadProject() in .\Yafc\Windows\WelcomeScreen.cs:line 396
```

**Comment by DaleStan** [comment]
This was fixed in #364, which just missed the cutoff for 2.4.0. I think it
can also be fixed by updating py postprocessing.

If you can't update pypp and you're comfortable editing json, you can
unbrick the project by deleting the first line containing `mova-plant`, but
mova will just go back to being inaccessible if you do that.

**Comment by shpaass** [comment]
I'll make a new release.

**Comment by sunrosa** [comment]
2.5.0 fixes the issue. No manual editing of the save file was necessary.
