### ISSUE TITLE
Failed Start on an Applie Silicon Mac

### ISSUE THREAD

**Issue by AnakinShieh** [shpaass/yafc-ce#90]
version 6.3 rc

error message:
```
Unhandled exception. System.DllNotFoundException: Unable to load shared library 'libSDL2.dylib' or one of its dependencies. In order to help diagnose loading problems, consider setting the DYLD_PRINT_LIBRARIES environment variable: dlopen(liblibSDL2.dylib, 0x0001): tried: 'liblibSDL2.dylib' (no such file), '/System/Volumes/Preboot/Cryptexes/OSliblibSDL2.dylib' (no such file), '/usr/lib/liblibSDL2.dylib' (no such file, not in dyld cache), 'liblibSDL2.dylib' (no such file), '/usr/local/lib/liblibSDL2.dylib' (no such file), '/usr/lib/liblibSDL2.dylib' (no such file, not in dyld cache)
   at System.Runtime.InteropServices.NativeLibrary.LoadByName(String libraryName, QCallAssembly callingAssembly, Boolean hasDllImportSearchPathFlag, UInt32 dllImportSearchPathFlag, Boolean throwOnError)
   at System.Runtime.InteropServices.NativeLibrary.LoadLibraryByName(String libraryName, Assembly assembly, Nullable`1 searchPath, Boolean throwOnError)
   at System.Runtime.InteropServices.NativeLibrary.Load(String libraryName, Assembly assembly, Nullable`1 searchPath)
   at YAFC.YafcLib.DllResolver(String libraryname, Assembly assembly, Nullable`1 searchpath) in C:\Users\Chill\Documents\git\have-fun\yafc-ce\YAFC\YafcLib.cs:line 59
   at System.Runtime.InteropServices.NativeLibrary.LoadLibraryCallbackStub(String libraryName, Assembly assembly, Boolean hasDllImportSearchPathFlags, UInt32 dllImportSearchPathFlags)
   at SDL2.SDL.SDL_Init(UInt32 flags)
   at YAFC.UI.Ui.Start() in C:\Users\Chill\Documents\git\have-fun\yafc-ce\YAFCui\Core\Ui.cs:line 29
   at YAFC.Program.Main(String[] args) in C:\Users\Chill\Documents\git\have-fun\yafc-ce\YAFC\Program.cs:line 13
zsh: abort      /Users/anakin/Data/OSX/YAFC

Saving session...
...copying shared history...
...saving history...truncating history files...
...completed.
```

I guess it's due to a misspelling of lib name?

**Comment by have-fun-was-taken** [comment]
Hi, thank you for letting us know.
I've met a similar error before. You can search for alterae's messages in #yafc-dev on Pyanodon [Discord](https://discord.gg/b5VergGq75).
One of the ways to affect that error is to change the [mapping](https://github.com/have-fun-was-taken/yafc-ce/blob/master/YAFC/YafcLib.cs#L41) of lib names for OSX.

**Comment by shpaass** [comment]
We've [added](<https://github.com/shpaass/yafc-ce/pull/191>) arm64 into our list of distributives. Please reopen the issue if the problem persists.
